dist: xenial
os: linux
language: shell

services:
  - docker

script:
  - docker run
    -v $TRAVIS_BUILD_DIR:/build
    -v $TRAVIS_BUILD_DIR/build.sh:/build.sh
    -v $TRAVIS_BUILD_DIR/inputs.list:/inputs.list
    -w /build
    --entrypoint=./build.sh
    centos:7.7.1908

deploy:
  provider: releases
  token:
    secure: CjQWpOlALnttLEGuK5AzjaMNCRayyFC4KYbD95U5HFjxSgNUmtNDC0dISmQF2h9Qw0MoXMsR1FnMO3liIX2N4mp/BOy/rOS0wibPMXwuAR6g4jL2DQWIi1UYAH/rrDN1rBe3+FAEtGGyh1jKZrmTxrOfufXf8ZYLz3UG2APStxeoaJY9OAPuE1LMb5wZR35sJvZVzvewxaFmTbDg1Uim3+zC5/FtmTZjTmK3jMdYLDek/nFdIa1MFxOmNtyhKhYHaO2CslD0yRlUU0iIKtLTrmbSIMAdFy0+x1xNDcd+HUVEx3OJRGaQquQDPcrHI0hOyKSHk42j54umlh4TAMnQ6JB6dKVjKhRUEWZTrnW284L/dGpkLGaVfCxh0apNN/Mul7PZSBBWWJ7Gv3+3nq1Jx/qmmofjAbuHs8iiJSnL+SN5y+DO9p9di2ECY+kuorBTo+ssQM0C/C+ppRZoS6a5BOXnAzQpY5VyV69OLjt0kVhYkAn2FNnPgJBLim5bR0xHDs5vFEhwfSW9JatdVqWF2G+UxCfr714qo3s6ZaphRDw8sL5YwyL8ugL+IBxOnhr9/mep2uKACl4Qch35HCG92c47ZvEO8+G67yBAhwqMCtIzx3oV3qsX5Ox7kDxx43ZE9HQVt/seQMTFOWwiY7WClJsCna3PR0IJPLRmLAobs7M=
  file_glob: true
  file: ./*.rpm
  cleanup: false
  on:
    tags: true
